### ISSUE TITLE
Add zoom/viewport adjustement

### ISSUE THREAD

**Issue by TheAdamSmith** [TheAdamSmith/precursor#15]
We should add the ability to zoom or adjust the viewport while playing the game. This will be helpful for dev testing and will let us get a better feel for what the actual camera setting should be

**Comment by mitchellkazin15** [comment]
So this can be done with project -> project settings -> window -> mode = windowed. I set it to fullscreen in my PR, but we can change it back. Is that sufficient for this ticket, or do you also want in game options to change this?
