### ISSUE TITLE
Figure out how to do inheritance/Composition

### ISSUE THREAD

**Issue by TheAdamSmith** [TheAdamSmith/precursor#16]
Figure out to properly do inheritance/composition.

My java pilled brain wants to refactor different things into "classes" that can be re-used through inheritance/instancing, but according to this reddit post https://www.reddit.com/r/godot/comments/129sgc8/what_is_the_intended_workflow_for_inheriting/ that is not the correct way to go about development in godot. 

So we should figure out how to properly do composition as a template for a lot of the scenes we will be building. For example, we will have several different enemy types that will all have HP and some sort of pathing. We should be able to create multiple enemy types with out recreating the pathing/HP logic for each different enemy. 

A potential good resource is this video that I have not yet watched https://www.youtube.com/watch?v=W8gYHTjDCic

**Comment by mitchellkazin15** [comment]
I think this can be closed as OBE
